mymap/markers/urls.py
from django.urls import path
from .views import MarkersMapView, MarkersAddView, MarkerCreateView, MarkerListView, LineListView, LineCreateView
from .views import LinesAddView

app_name = 'markers'

urlpatterns = [
    path('map/', MarkersMapView.as_view(), name='map'),
    path('map/add_marker', MarkersAddView.as_view(), name='add_marker'),
    path('map/add-line', LinesAddView.as_view(), name='add-line'),
    path('map/create-marker/', MarkerCreateView.as_view(), name='create-marker'),
    path('map/create-line/', LineCreateView.as_view(), name='create-line'),
    path('map/marker-list/', MarkerListView.as_view(), name='marker-list'),
    path('map/line-list/', LineListView.as_view(), name='line-list'),
]

mymap/mymap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('markers.api')),
    path('markers/', include('markers.urls')),
]

mymap/markers/models.py
from django.db import models
from django.contrib.gis.db import models


class Marker(models.Model):
    name = models.CharField(max_length=255)
    location = models.PointField()

    def __str__(self):
        return self.name


class Line(models.Model):
    name = models.CharField(max_length=255)
    location = models.LineStringField()

mymap/markers/views.py
from django.views.generic import TemplateView
from .models import Marker, Line
from rest_framework import generics
from .serializers import MarkerSerializer, LineSerializer
from rest_framework_gis import filters


class MarkersMapView(TemplateView):
    template_name = 'map.html'


class MarkersAddView(TemplateView):
    template_name = 'add_marker.html'


class LinesAddView(TemplateView):
    template_name = 'add-line.html'


# New marker
class MarkerCreateView(generics.CreateAPIView):
    queryset = Marker.objects.all()
    serializer_class = MarkerSerializer


# Marker list
class MarkerListView(generics.ListAPIView):
    queryset = Marker.objects.all()
    serializer_class = MarkerSerializer


class LineCreateView(generics.CreateAPIView):
    queryset = Line.objects.all()
    serializer_class = LineSerializer


class LineListView(generics.ListAPIView):
    queryset = Line.objects.all()
    serializer_class = LineSerializer
    bbox_filter_field = 'location'
    filter_backends = [filters.InBBOXFilter]

mymap/markers/templates/add-line.html
{% load static %}
<html lang="en">
    <head>
        <title>Markers Map</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" type="text/css" href="{% static 'map.css' %}" />
        <link rel="stylesheet" type="text/css" href="//unpkg.com/leaflet/dist/leaflet.css" />
        <script src="//unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    </head>
    <body>
        <div id="menu">
            <form action="{% url 'markers:map' %}">
                <input type="submit" value="Return to map view" id="menu-button" />
            </form>
        </div>
        {{ markers|json_script:"markers-data" }}
        <div id="map"></div>
        <script src="{% static 'map.js' %}"></script>
        <script src="{% static 'map_add_line.js' %}"></script>
    </body>
</html>

mymap/markers/templates/add_marker.html
{% load static %}
<html lang="en">
    <head>
        <title>Markers Map</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" type="text/css" href="{% static 'map.css' %}" />
        <link rel="stylesheet" type="text/css" href="//unpkg.com/leaflet/dist/leaflet.css" />
        <script src="//unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    </head>
    <body>
        <div id="menu">
            <form action="{% url 'markers:map' %}">
                <input type="submit" value="Return to map view" id="menu-button" />
            </form>
        </div>
        {{ markers|json_script:"markers-data" }}
        <div id="map"></div>
        <script src="{% static 'map.js' %}"></script>
        <script src="{% static 'map_add_marker.js' %}"></script>
    </body>
</html>

mymap/markers/templates/map.html
{% load static %}
<html lang="en">
    <head>
        <title>Markers Map</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" type="text/css" href="{% static 'map.css' %}" />
        <link rel="stylesheet" type="text/css" href="//unpkg.com/leaflet/dist/leaflet.css" />
        <script src="//unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    </head>
    <body>
        <div id="menu">
            <form action="{% url 'markers:add_marker' %}">
                <input type="submit" value="Add new marker to the map" class="menu-button" />
            </form>
            <form action="{% url 'markers:marker-list' %}">
                <input type="submit" value="Marker list" class="menu-button" />
            </form>
        </div>
        {{ markers|json_script:"markers-data" }}
        <div id="map"></div>
        <script src="{% static 'map.js' %}"></script>
    </body>
</html>